# Generated by Django 5.1.6 on 2025-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deedinformation',
            old_name='description',
            new_name='legal_description',
        ),
        migrations.RemoveField(
            model_name='deedinformation',
            name='easements',
        ),
        migrations.RemoveField(
            model_name='deedinformation',
            name='references',
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='deed_book',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='deed_page',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='map_book',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='map_page',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='subdivision',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deedinformation',
            name='township',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
